- tests/no_std_build.rs
Re: gz/rust-x86#1
THIS IS EXPECTED TO BREAK TRAVIS CI. :-)
This will cause `cargo test` to fail if any lang_items are being pulled
in by supporting crates.  This code is designed to simulate a typical OS
kernel written in Rust, using `#[no_std]` and custom `lang_items`.
Tested against rustc 1.6.0-nightly (cc3094872 2015-11-11).
Fixing this will make it much easier for beginner Rust OS developers to
use libx86 in more configurations.  But I haven't figured out what's
causing the error yet, only how to reproduce it.
Thank you for working on such a useful library!
> Add a test to reproduce link errors reported in gz/rust-x86#1

- src/irq.rs
- src/lib.rs
(Here are the constructors I promised you. Thank you!)
It's really easy to create invalid IdtEntry values, and doing so usually
results in triple faults.  So in order to reduce kernel developer pain,
we provide two ready-made constructors:
1. A `missing` constructor, which can be used for unimplemented IDT
entries.  This is a `const` fn, making it possible to statically-
initialize an IdtEntry table at compile time.  (Note that we
can't use `Default::default` for this, because trait methods can't
be `const`.)
2. A `new` constructor, which takes a GDT code segment offset and
a pointer to an interrupt handler, and installs it using the default
flags.
> Add convenience constructors for IdtEntry

- src/lib.rs
- src/tlb.rs
Adds a rudimentary module for flushing the translation lookaside buffer (TLB). The `flush` function uses the `invlpg` instruction and the `flush_all` function reloads the CR3 register.
> Add a TLB module

- src/paging.rs
https://aturon.github.io/features/types/newtype.html
This provides some extra type safety by providing explicit constructions
and conversions of the PAddr and VAddr types. No runtime overhead.
> Use newtypes for PAddr and VAddr

- Cargo.toml
- build.rs
- src/lib.rs
The first commit disables the `perfcnt` module and related code generation by default to improve compile times. It adds a `performance-counter` cargo feature to enable it again.
The second commit just indents the body of the new `performance_counter` module in `build.rs`.
Fixes #9
> Make `perfcnt` module optional

- src/segmentation.rs
I hope that the inline assembly and the `Selector::from_raw` function are correct here…
> Add method to retrieve current code segment selector

- src/irq.rs
This commit changes the intterupt_gate() constructor to 1) use a Vaddr
instead of a raw pointer for the interrupt handler and 2) declare it as
a const_fn.
> Modify irq::interrupt_gate() signature

- Cargo.toml
I'd like to mention @Tobba too, but there are no authors in cpu's `Cargo.toml`.
> Add myself to authors list, if you don't mind :)

- src/shared/segmentation.rs
According to the mentioned Intel 3a, Section 3.4.2 "Segment Selectors", the TI bit is bit 2.
> Fix TableIndicator bit offset

- src/shared/segmentation.rs
- src/shared/task.rs
This fixes the build error on latest nightly.
See rust-lang/rust#39083 and especially [this comment](https://github.com/rust-lang/rust/issues/39083#issuecomment-272935193) for details.
> Structures are not considered immediates anymore

- src/shared/control_regs.rs
CR3 contains the physical address of the root of the page table
structure. In 32-bit protected mode with PAE, physical addresses can
be 52-bits long. To accomodate this, CR3 should always be a u64.
> Make CR3 a u64 not a usize

- src/lib.rs
Associated consts are stable as of Rust 1.20, there is no longer a need to add a `#![feature(...)]` attribute for them.
> Remove `#![feature(associated_consts)]`

- test_harness/src/lib.rs
It is required after commit https://github.com/rust-lang/rust/commit/60dd83ea85853f6a31f8998eb80ce47446fdb785 .
> Add 'allow_fail' field into 'TestDesc' struct.

- src/bits32/mod.rs
- src/bits32/segmentation.rs
- src/bits64/mod.rs
- src/bits64/segmentation.rs
- src/bits64/task.rs
- src/shared/descriptor.rs
- src/shared/segmentation.rs
- Provide two functions new_memory and new_tss to comfortably create memory and TSS descriptors.
The x86-64 version of new_tss outputs an array of 2 descriptors to account for the upper bits of the TSS pointer address.
- Add a bitness parameter to the x86-64 version of new_memory to allow creating segments for 32-bit and 64-bit code.
- Fix a copy-pasta mistake in the x86 version of set_cs.
- Fix the SegmentDescriptor type flag.
I'm fully aware that these API changes are not backwards compatible. However, the merge with libcpu has already broken the API before and the x86 crate couldn't be used for x86-64 anymore since then. There simply wasn't a way to create a memory segment for 64-bit code.
My changes have been tested with https://github.com/ColinFinck/HermitCore/tree/path2rs
Fixes #25 …
> Split up shared::segmentation into bits32::segmentation and bits64::segmentation and implement specifics of each architecture

- src/bits64/mod.rs
I also don't see how these are x86-64-specific, so they should be removed either way.
> Remove unused macros causing compiler warnings.

- src/bits32/segmentation.rs
- src/bits64/irq.rs
Additionally, replace the boolean "block" by a more straightforward "ty" parameter with custom type.
Due to the custom type and assert!, we cannot keep this a "const fn", but I think code correctness outweighs this.
> Update IdtEntry to the actual descriptor in Intel 3a, Figure 6-7 (including ist_index)

- src/controlregs.rs
- src/lib.rs
- src/time.rs
The addition of some intrinsics in `core::arch` means that we no longer have to use inline assembly in some cases.
I've changed `rdtsc`'s signature to match the one in `core::arch` & Intel's docs.
Please tell me if there's some other `core::arch` function which I've missed and we could use it in this crate.
> Use the core::arch intrinsics where possible

- src/controlregs.rs
This patch add the function cr2_write, which I use to reset the control register CR2.
> add cr2_write, for example to reset CR2

- src/bits64/rflags.rs
This patch removes only a typo in the specification of the target architecture.
> use x86_64 instead x86-64 as architecture target

- build.rs
- x86data/perfmon_data/mapfile.csv
* build is failing on new perfmon_data due to several issues
* handles some cases better
* add better failure messaging
* remove any problematic microarchitectures
Unaddressed:
* PEBSCounter values in goldmontplus exceed 8 ("EventName": "INST_RETIRED.ANY", "PEBScounters": "32")
* skylakex and casecadelakex produce collision
* KNL and KNM also produces a collision
> perfmon_data update broke build

- src/io.rs
Rust wont inline functions from other crates unless you add the `#[inline]` marker to the function. Also some function's doc comments were used `//` instead of `///` so the comment wasnt being used as a doc comment.
> Make io assembly inlinable and fix doc comments

- src/bits32/eflags.rs
- src/bits64/rflags.rs
Non-inlined functions have a [function prologue](https://en.wikipedia.org/wiki/Function_prologue) that contain instructions which can mess with the FLAGS register before we have a chance to read it.
> Always inline functions that operate on FLAGS register

- src/segmentation.rs
- src/task.rs
Currently only CS can be read using `x86::segmentation::cs()`.
This PR adds functions to read the other 5 registers and to read the TR (task register).
> Provide functions to read ES, SS, DS, FS, GS and TR segment registers

- src/bits64/mod.rs
- src/bits64/vmx.rs
- src/lib.rs
- src/vmx/mod.rs
- src/vmx/vmcs.rs
This includes most of the VMX instructions and all VMCS field constants as of
[325384-070US (May 2019) Volume 3](https://web.archive.org/web/20190921135821/https://software.intel.com/sites/default/files/managed/a4/60/325384-sdm-vol-3abcd.pdf) version of Intel SDM.
VMFUNC and VMCALL were not included due to them being too application-specific
and INVEPT and INVVPID are simply left out to be implemented later.
> VMX support

- src/vmx/vmcs.rs
[325384-070US (May 2019)](https://web.archive.org/web/20190921135821/https://software.intel.com/sites/default/files/managed/a4/60/325384-sdm-vol-3abcd.pdf) version of Intel SDM was used.
> Provide bit constants for common VM-execution control fields

- src/bits64/vmx.rs
In #56's discussion I noted that "there are no strong reasons to use inline for VMX intrinsics".
I was wrong: it's practically impossible to use `x86::bits64::vmx::vmresume()` due to it being a function. The reason is that VMRESUME is usually called after restoring the guest state, which includes stack pointer.
As the stack pointer now corresponds to guest address space and CALL to `x86::bits64::vmx::vmresume()` accesses the stack, this results in triple fault exception.
`x86::bits64::vmx::vmlaunch()` was also inlined because in practice it has similar pitfalls, and even through they can be avoided, an inlined version of this function is less surprising.
> Inline vmresume() and vmlaunch()

- src/lib.rs
`repr_transparent` became stable in [1.28](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1280-2018-08-02)
`const_fn` in [1.31](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html)
I dream of a world, where system level programming can be done in stable rust :smile:
> removed #\[feature(const_fn, repr_transparent)] as these are now stable

- .github/dependabot.yml
- Cargo.toml
Dependabot should check if all dependencies are up to date once a day. I
added the .github folder to the exclude section of the crate so it will
not get uploaded to crates.io.
> Dependabot config to keep the dependencies updated

- .github/workflows/standard.yml
- Cargo.toml
- build.rs
- x86test/Cargo.toml
- x86test/x86test_types/Cargo.toml
It looks like I broke the performance-counter feature when updating the dependencies with #71 Sorry for that. This pull requests fixes this feature and also fixes the tests for the default and the performance-counter feature. Running `cargo test --all-features` still fails, but as far as I can tell, this also was the case before #71.
I have also added a GitHub Action config so that the master branch and every PR are automatically builds with default features and with all features. I hope this prevents anyone from breaking a non-default feature in the future. Again, sorry for that.
> Fix performance-counter feature

- src/bits64/paging.rs
When dealing with DMA-capable devices, we have an additional address
type beyond virtual and physical addresses. This commit adds the IOAddr
as a distinct type. Device drivers use this address to communicate the
location of descriptor queues and buffers to the device.
Currently, this is a copy of the physical address. However, in the
future we might add IOMMU support where the IOAddr will be configurable.
Signed-off-by: Reto Achermann <achreto@gmail.com>
> types: adding ioaddr type to paging module

- src/dtables.rs
- x86test/src/lib.rs
Fixes compiler errors and warnings that can appear on the latest nightly for the `x86` crate.
For more details see
- https://github.com/rust-lang/rust/issues/82523 about referencing packed/unaligned fields, and
- https://github.com/rust-lang/rust/issues/84510 about the removal of the `const_fn` feature gate.
> Fix the build for nightly

- src/bits32/mod.rs
- src/bits32/paging.rs
This is almost a copy of `src/bits64/paging.rs` (including utests).
Changes from 64bit one:
- u64 -> u32
- In 32bit, PAGE_SIZE_ENTRIES is 1024 because entry is 32bit length
- Page directory index and page table index are 10bit length (`pd_index`, `pt_index`)
- ADDRESS_MASK just turn off flag bits
- Variables and structures about page directory pointer table is removed
I'm not knowledgeable about x86 architecture, so there may be a mistake.
Question: Why does only VAddr have as_mut_ptr and as_ptr?
> Add structures for 32bit paging

- src/perfcnt/intel/mod.rs
The new `model_id` function introduced as part of [this commit ](https://github.com/gz/rust-cpuid/commit/97fd82ea59b7d2ad933631dbc8ae8939845ce756) breaks the `COUNTER_MAP` lookup on https://github.com/gz/rust-perfcnt which depends on `rust-x86` crate.
> perfcnt: Use `base_model_id` for looking up `COUNTER_MAP`

- src/debugregs.rs
- src/irq.rs
- src/lib.rs
- src/task.rs
- src/tlb.rs
The new asm!() syntx has been stabilized in
nightly Rust, but requires either a `use`
statement or explicit package qualification.
This PR adds `use` statements in the modules
that use the new macro.  Fixes #117.
Signed-off-by: Dan Cross <cross@gajendra.net>
> Add explicit `use` statements core::arch::asm.

- src/bits32/eflags.rs
- src/bits32/mod.rs
- src/bits32/segmentation.rs
- src/bits64/registers.rs
- src/bits64/rflags.rs
- src/bits64/segmentation.rs
- src/bits64/sgx.rs
- src/bits64/syscall.rs
- src/bits64/vmx.rs
- src/controlregs.rs
- src/dtables.rs
- src/fence.rs
- src/io.rs
- src/lib.rs
- src/msr.rs
- src/segmentation.rs
- x86test/Cargo.toml
- x86test/README.md
I got a number of compile failures with `llvm_asm`
with the latest nightly.  Instead of figuring out
how to fix that, I just went ahead and finished
converting everything to use `asm`, which has the
added bonus of being stable, anyway!
I'm not entirely sure this is all correct;
`cargo test` seems to drag in an explicit
dependency on x86-0.44.0, which still fails.
Note also that the SGX modifications are a bit
more elaborate than what had been there; apparently
LLVM uses the %rbx internally, even though the
instructions exposed in that module use that
register.  I worked around that by pushing %rbx
and then copying the leaf operand from %rsi to
%rbx and copying %rbx _back_ to %rsi for output
and popping the original value of %rbx.  The
input/output operands are then writen in terms
of …
> Finish converting to new asm!() syntax.

- src/apic/xapic.rs
- src/lib.rs
closes https://github.com/gz/rust-x86/issues/126
I couldnt change the rust-toolchain file in this PR because of the circular dependency with x86test
> Remove remaining usages of nightly features

- src/apic/xapic.rs
The use of 'static lifetime for the MMIO access is unecessary and prevents normal use of the XAPIC object in a variety of situtations, such as those with a limited-lifetime virtual memory mapping.
Using a non-static lifetime for MMIO access allows greater flexibilty.
> xapic: Use non-static lifetime
